apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s_resources/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: django
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: django
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s_resources/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/skin-cancer-prediction-django-default: "true"
        io.kompose.service: django
    spec:
      containers:
        - args:
            - python3
            - manage.py
            - runserver
            - 0.0.0.0:8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: proj.settings
          image: vivekmaltare/spe_major_project:latest
          name: django
          ports:
            - containerPort: 8000
              hostPort: 8000
              protocol: TCP
      restartPolicy: Always
