apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o k8s_resources/
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o k8s_resources/
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/skin-cancer-prediction-django-default: "true"
        io.kompose.service: logstash
    spec:
      containers:
        - args:
            - logstash
            - -f
            - /usr/share/logstash/pipeline/logstash.conf
          image: docker.elastic.co/logstash/logstash:7.10.2
          name: logstash
          ports:
            - containerPort: 5000
              hostPort: 5000
              protocol: TCP
            - containerPort: 9600
              hostPort: 9600
              protocol: TCP
          volumeMounts:
            - mountPath: /usr/share/logstash/pipeline/logstash.conf
              name: logstash-cm0
              subPath: logstash.conf
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: logstash.conf
                path: logstash.conf
            name: logstash-cm0
          name: logstash-cm0
