apiVersion: v1
data:
  logstash.conf: |
    input {
      tcp {
        port => 5000
        codec => json
      }
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch:9200"]
      }
    }
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: logstash
  name: logstash-cm0
